server:
  port: 8060

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/davinchicoder
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/api/v1/employees/**
            - id: department-service
              uri: lb://department-service
              predicates:
                - Path=/api/v1/departments/**
  cache:
    type: caffeine